# Generated by Django 3.1.5 on 2021-01-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210127_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('REA', 'Realizada')], default='PEN', max_length=3),
        ),
    ]
